version: "3.7"

services:

  influxdb:
    image: influxdb:1.7.8
    volumes:
      - influxdb-data:/var/lib/influxdb
    ports:
      - "8086:8086"    
    networks:
      - tick
    environment:
      HOST: 0.0.0.0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]      

  chronograf:
    image: quay.io/influxdb/chronograf:1.7.14
    volumes:
      - ./config/chronograf:/var/lib/chronograf
    ports:
      - "8888:8888"
    networks:
      - tick
    environment: 
      HOST: 0.0.0.0
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    depends_on: 
      - influxdb
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]      

  kapacitor:
    image: kapacitor:1.5.3
    ports:
      - "9092:9092"
    volumes: 
      - ./config/kapacitor:/etc/kapacitor
    networks:
      - tick
    environment: 
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    deploy:
      mode: replicated
      replicas: 1

volumes:
  influxdb-data:


networks:
  tick:
    # driver: bridge
    # driver_opts:
      # encrypted: "true"